const Menu = [
  {
    id: 1,
    image: "images/maggie.jpg",
    name: "maggi",
    category: "breakfast",
    price: "12₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 2,
    image: "images/aloo.jpg",
    name: "aloo pakoda",
    category: "evening",
    price: "20₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "10₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 4,
    image: "images/chola.jpg",
    name: "chola",
    category: "lunch",
    price: "50₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 5,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "80₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 6,
    image: "images/thali.jpg",
    name: "Veg Thali",
    category: "dinner",
    price: "180₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 7,
    image: "images/jamun.jpg",
    name: "Sweets",
    category: "dinner",
    price: "60₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 8,
    image: "images/rice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 9,
    image: "images/samosa.jpg",
    name: "Samosa",
    category: "evening",
    price: "10₹",
    describption: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
];

export default Menu;
